version: '3'
services:
    php-apache:
        build:
            context: ./php-apache
        ports:
            - 8080:80
        volumes:
            - ./WWW:/var/www/html
    db:
        build:
            context: ./sql
        volumes:
            - ./sql:/var/lib/mysql
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: secret